title: Tailwind Jekyll Starter Kit
description: A starter kit for using Tailwind with Jekyll

plugins:
  - jekyll-feed
  - jekyll-purgecss
author: "Jonathan Simmons"
url: "jonathansimmons.dev"
title: "Jonathan Simmons"
description: "The personal site of Jonathan Simmons. Husband / Father / Product Strategist"
twitter:
  username: "jonathansimmons"
logo: "images/avatar.jpg"
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
